Repository empress/ember-cli-showdown, pull requests merged in 2024-01, with the labels that each got.

#129 add lint-to-the-future dashboard
  .github/workflows/lint-to-the-future.yml
Labels: internal

#132 setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#135 update lint-to-the-future dashboard action
  .github/workflows/lint-to-the-future.yml
Labels: internal

#136 drop support for Ember < 3.16
  .github/workflows/ci.yml
  README.md
Labels: breaking

#131 Convert to Glimmer component
  .tool-versions
  addon/components/markdown-to-html.hbs
  addon/components/markdown-to-html.js
  addon/templates/components/markdown-to-html.hbs
  tests/dummy/app/templates/application.hbs
  tests/integration/components/markdown-to-html-test.js
Labels: enhancement
