Repository empress/ember-cli-showdown, pull requests merged in 2024-02, with the labels that each got.

#138 Update README.md to reflect the changes in 8.0.0
  README.md
Labels: documentation

#141 update to v5.4 with ember-cli-update
  .ember-cli
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .watchmanconfig
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  tests/integration/components/markdown-to-html-test.js
  tsconfig.declarations.json
Labels: internal

#143 update showdown to v2
  package.json
  pnpm-lock.yaml
Labels: enhancement

#144 drop support for node 16
  .github/workflows/ci.yml
  README.md
Labels: breaking
